### ISSUE TITLE
Errors during compilation

### ISSUE THREAD

**Issue by abhi18av** [tech-no-crat/Cadventure-txt#1]
Hii @tech-no-crat 

Hey, I'm trying to run this game but it give me the following error on running `gcc Cadventure-txt.c -o cadventure
`

```
Cadventure-txt.c:97:42: warning: unsequenced modification and
      access to 'k' [-Wunsequenced]
  ...name[k++] = story[i][j+k];
           ^                ~
Cadventure-txt.c:158:65: warning: unsequenced modification and
      access to 'l' [-Wunsequenced]
  ...|| story[i][j+l]==' ') name[l++] = story[i][j+l];
                                  ^                ~
2 warnings generated.
Undefined symbols for architecture x86_64:
  "_is_command", referenced from:
      _init in Cadventure-txt-1fe852.o
      _play in Cadventure-txt-1fe852.o
  "_is_letter", referenced from:
      _init in Cadventure-txt-1fe852.o
      _play in Cadventure-txt-1fe852.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

Please let me know if this is a n00b mistake 👍

**Comment by tech-no-crat** [comment]
Hello abhi18av! I just fixed the issues you're having. Please note that this is a program I wrote years ago, when I was still learning C, and it is not very maintainable or well written.

About the issues you were having:

- The first two messages are not errors, but warnings, so they should not be blocking compilation. This particular warning is pretty important, so I fixed it.
- The last error is a linker error complaining about undefined function references to two inlined functions. I don't completely understand what's happening exactly, but I removed the inline specifier from the functions (because there's no real reason to inline them anyway), so you should be fine.

I'm closing the issue, feel free to reopen if it persists.

**Comment by abhi18av** [comment]
Yup, @tech-no-crat now it's works smoothly! Thanks, I appreciate the quick response :)
